'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Add_New_Code
    
    '''<summary>
    '''DropDownList1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownList1 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txt_System_Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_System_Name As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txt_Code control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Code As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txt_Bit9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Bit9 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txt_Bit10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Bit10 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txt_Bit11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Bit11 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txt_Bit12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Bit12 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txt_Bit13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Bit13 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txt_Bit14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Bit14 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txt_Bit15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Bit15 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txt_Bit16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Bit16 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txt_Bit17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Bit17 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txt_Bit18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Bit18 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txt_Bit19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Bit19 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txt_Bit20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Bit20 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txt_Bit21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Bit21 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txt_Bit22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Bit22 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txt_Bit23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Bit23 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txt_Bit24 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Bit24 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txt_Bit25 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Bit25 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txt_Bit26 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Bit26 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txt_Bit27 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Bit27 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txt_Bit28 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Bit28 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txt_Bit29 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Bit29 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txt_Bit30 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Bit30 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txt_Bit31 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Bit31 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txt_Bit32 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Bit32 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txt_SDI00 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_SDI00 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txt_SDI01 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_SDI01 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txt_SDI10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_SDI10 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txt_SDI11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_SDI11 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txt_SSM00 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_SSM00 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txt_SSM01 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_SSM01 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txt_SSM10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_SSM10 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txt_SSM11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_SSM11 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''btn_update control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_update As Global.System.Web.UI.HtmlControls.HtmlButton
End Class
